### ISSUE TITLE
empapp-test  leckénél van egy felesleges pont a sor végén a beans.xml-ben, ami buildelési hibát okoz

### ISSUE THREAD

**Issue by petrep** [Training360/javax-ee-public#16]
[link](https://github.com/Training360/javax-ee-public/blob/master/demos/empapp-test/src/main/resources/META-INF/beans.xml#L5)

**Comment by vicziani** [comment]
Köszi, javítottam.

**Comment by vicziani** [comment]
Pontok eltávolításra kerültek.
